# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t1(self):
    self.driver.get("https://khamko07.github.io/TestFiNalKTPM/")
    self.driver.set_window_size(1054, 800)
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("Mettachit")
    self.driver.find_element(By.ID, "lastName").click()
    self.driver.find_element(By.ID, "lastName").send_keys("Sysomephone")
    self.driver.find_element(By.ID, "regUsername").click()
    self.driver.find_element(By.ID, "regUsername").send_keys("nut09")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("Mettachit789@gmail.com")
    self.driver.find_element(By.ID, "regPassword").click()
    self.driver.find_element(By.ID, "regPassword").send_keys("Mettachit123@//")
    self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(5) > .fas").click()
    self.driver.find_element(By.ID, "confirmPassword").click()
    self.driver.find_element(By.ID, "confirmPassword").send_keys("Mettachit123@//")
    self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(6) > .fas").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(7)").click()
    assert self.driver.switch_to.alert.text == "Registration successful!"
    self.driver.find_element(By.ID, "loginUsername").click()
    self.driver.find_element(By.ID, "loginUsername").send_keys("nut09")
    self.driver.find_element(By.ID, "loginPassword").click()
    self.driver.find_element(By.ID, "loginPassword").click()
    self.driver.find_element(By.ID, "loginPassword").send_keys("Mettachit123@//")
    self.driver.find_element(By.CSS_SELECTOR, ".fa-eye").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
  
